# .github/workflows/teste-rapido.yml
name: Teste rápido

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Teste simples
        run: echo "Está funcionando!"
